export const iconOptions = [
    { name: 'Pork', uri: require('@/assets/images/pork.png') },
    { name: 'Beef', uri: require('@/assets/images/beef.png') },
    { name: 'Chicken', uri: require('@/assets/images/chicken.png') },
    { name: 'Alcohol', uri: require('@/assets/images/alcohol.png') },
    { name: 'Bread', uri: require('@/assets/images/bread.png') },
    { name: 'Canned Food', uri: require('@/assets/images/canned-food.png') },
    { name: 'Cereal', uri: require('@/assets/images/cereals.png') },
    { name: 'Snacks', uri: require('@/assets/images/chips.png') },
    { name: 'Coffee', uri: require('@/assets/images/coffee.png') },
    { name: 'Condiments', uri: require('@/assets/images/condiment.png') },
    { name: 'Seafood', uri: require('@/assets/images/crustacean.png') },
    { name: 'Eggs', uri: require('@/assets/images/egg.png') },
    { name: 'Fish', uri: require('@/assets/images/fish.png') },
    { name: 'Flour', uri: require('@/assets/images/flour.png') },
    { name: 'Jam', uri: require('@/assets/images/jam-jar.png') },
    { name: 'Milk', uri: require('@/assets/images/milk.png') },
    { name: 'Noodles', uri: require('@/assets/images/noodle.png') },
    { name: 'Oil', uri: require('@/assets/images/oil.png') },
    { name: 'Pastry', uri: require('@/assets/images/pastry.png') },
    { name: 'Salami', uri: require('@/assets/images/salami.png') },
    { name: 'Sausages', uri: require('@/assets/images/sausage.png') },
    { name: 'Soft Drink', uri: require('@/assets/images/soft-drink.png') },
    { name: 'Spaghetti', uri: require('@/assets/images/spaghetti.png') },
    { name: 'Tea', uri: require('@/assets/images/tea.png') },
    { name: 'Vegetables', uri: require('@/assets/images/vegetables.png') },
    { name: 'Spices', uri: require('@/assets/images/spices.png') },
    // Add more icons as needed
  ];